/* 
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 6.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

namespace AdobeSign.Rest.Test.Model.Groups
{
    /// <summary>
    ///  Class for testing GroupsInfo
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class GroupsInfoTests
    {
        // TODO uncomment below to declare an instance variable for GroupsInfo
        //private GroupsInfo instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of GroupsInfo
            //instance = new GroupsInfo();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of GroupsInfo
        /// </summary>
        [Test]
        public void GroupsInfoInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" GroupsInfo
            //Assert.IsInstanceOfType<GroupsInfo> (instance, "variable 'instance' is a GroupsInfo");
        }


        /// <summary>
        /// Test the property 'GroupInfoList'
        /// </summary>
        [Test]
        public void GroupInfoListTest()
        {
            // TODO unit test for the property 'GroupInfoList'
        }
        /// <summary>
        /// Test the property 'Page'
        /// </summary>
        [Test]
        public void PageTest()
        {
            // TODO unit test for the property 'Page'
        }

    }

}
