/* 
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 6.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

namespace AdobeSign.Rest.Test.Model.Webhooks
{
    /// <summary>
    ///  Class for testing WebhookLibraryDocumentEvents
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class WebhookLibraryDocumentEventsTests
    {
        // TODO uncomment below to declare an instance variable for WebhookLibraryDocumentEvents
        //private WebhookLibraryDocumentEvents instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of WebhookLibraryDocumentEvents
            //instance = new WebhookLibraryDocumentEvents();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of WebhookLibraryDocumentEvents
        /// </summary>
        [Test]
        public void WebhookLibraryDocumentEventsInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" WebhookLibraryDocumentEvents
            //Assert.IsInstanceOfType<WebhookLibraryDocumentEvents> (instance, "variable 'instance' is a WebhookLibraryDocumentEvents");
        }


        /// <summary>
        /// Test the property 'IncludeDetailedInfo'
        /// </summary>
        [Test]
        public void IncludeDetailedInfoTest()
        {
            // TODO unit test for the property 'IncludeDetailedInfo'
        }
        /// <summary>
        /// Test the property 'IncludeDocumentsInfo'
        /// </summary>
        [Test]
        public void IncludeDocumentsInfoTest()
        {
            // TODO unit test for the property 'IncludeDocumentsInfo'
        }

    }

}
