/* 
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 6.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

namespace AdobeSign.Rest.Test.Model.Workflows
{
    /// <summary>
    ///  Class for testing UserWorkflows
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class UserWorkflowsTests
    {
        // TODO uncomment below to declare an instance variable for UserWorkflows
        //private UserWorkflows instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of UserWorkflows
            //instance = new UserWorkflows();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of UserWorkflows
        /// </summary>
        [Test]
        public void UserWorkflowsInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" UserWorkflows
            //Assert.IsInstanceOfType<UserWorkflows> (instance, "variable 'instance' is a UserWorkflows");
        }


        /// <summary>
        /// Test the property 'UserWorkflowList'
        /// </summary>
        [Test]
        public void UserWorkflowListTest()
        {
            // TODO unit test for the property 'UserWorkflowList'
        }

    }

}
