/* 
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 6.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

namespace AdobeSign.Rest.Test.Model.Agreements
{
    /// <summary>
    ///  Class for testing AgreementEventList
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class AgreementEventListTests
    {
        // TODO uncomment below to declare an instance variable for AgreementEventList
        //private AgreementEventList instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of AgreementEventList
            //instance = new AgreementEventList();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of AgreementEventList
        /// </summary>
        [Test]
        public void AgreementEventListInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" AgreementEventList
            //Assert.IsInstanceOfType<AgreementEventList> (instance, "variable 'instance' is a AgreementEventList");
        }


        /// <summary>
        /// Test the property 'Events'
        /// </summary>
        [Test]
        public void EventsTest()
        {
            // TODO unit test for the property 'Events'
        }

    }

}
