/* 
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 6.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

namespace AdobeSign.Rest.Test.Model.Agreements
{
    /// <summary>
    ///  Class for testing CombinedDocumentPagesInfo
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class CombinedDocumentPagesInfoTests
    {
        // TODO uncomment below to declare an instance variable for CombinedDocumentPagesInfo
        //private CombinedDocumentPagesInfo instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of CombinedDocumentPagesInfo
            //instance = new CombinedDocumentPagesInfo();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of CombinedDocumentPagesInfo
        /// </summary>
        [Test]
        public void CombinedDocumentPagesInfoInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" CombinedDocumentPagesInfo
            //Assert.IsInstanceOfType<CombinedDocumentPagesInfo> (instance, "variable 'instance' is a CombinedDocumentPagesInfo");
        }


        /// <summary>
        /// Test the property 'DocumentPagesInfo'
        /// </summary>
        [Test]
        public void DocumentPagesInfoTest()
        {
            // TODO unit test for the property 'DocumentPagesInfo'
        }

    }

}
