/* 
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 6.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

namespace AdobeSign.Rest.Test.Model.Agreements
{
    /// <summary>
    ///  Class for testing DocumentsImageUrlsInfo
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class DocumentsImageUrlsInfoTests
    {
        // TODO uncomment below to declare an instance variable for DocumentsImageUrlsInfo
        //private DocumentsImageUrlsInfo instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of DocumentsImageUrlsInfo
            //instance = new DocumentsImageUrlsInfo();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of DocumentsImageUrlsInfo
        /// </summary>
        [Test]
        public void DocumentsImageUrlsInfoInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" DocumentsImageUrlsInfo
            //Assert.IsInstanceOfType<DocumentsImageUrlsInfo> (instance, "variable 'instance' is a DocumentsImageUrlsInfo");
        }


        /// <summary>
        /// Test the property 'OriginalDocumentsImageUrlsInfo'
        /// </summary>
        [Test]
        public void OriginalDocumentsImageUrlsInfoTest()
        {
            // TODO unit test for the property 'OriginalDocumentsImageUrlsInfo'
        }
        /// <summary>
        /// Test the property 'SupportingDocumentsImageUrlsInfo'
        /// </summary>
        [Test]
        public void SupportingDocumentsImageUrlsInfoTest()
        {
            // TODO unit test for the property 'SupportingDocumentsImageUrlsInfo'
        }

    }

}
