/* 
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 6.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

namespace AdobeSign.Rest.Test.Model.Agreements
{
    /// <summary>
    ///  Class for testing FormFieldConditionalAction
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class FormFieldConditionalActionTests
    {
        // TODO uncomment below to declare an instance variable for FormFieldConditionalAction
        //private FormFieldConditionalAction instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of FormFieldConditionalAction
            //instance = new FormFieldConditionalAction();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of FormFieldConditionalAction
        /// </summary>
        [Test]
        public void FormFieldConditionalActionInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" FormFieldConditionalAction
            //Assert.IsInstanceOfType<FormFieldConditionalAction> (instance, "variable 'instance' is a FormFieldConditionalAction");
        }


        /// <summary>
        /// Test the property 'Action'
        /// </summary>
        [Test]
        public void ActionTest()
        {
            // TODO unit test for the property 'Action'
        }
        /// <summary>
        /// Test the property 'AnyOrAll'
        /// </summary>
        [Test]
        public void AnyOrAllTest()
        {
            // TODO unit test for the property 'AnyOrAll'
        }
        /// <summary>
        /// Test the property 'Predicates'
        /// </summary>
        [Test]
        public void PredicatesTest()
        {
            // TODO unit test for the property 'Predicates'
        }

    }

}
