/* 
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 6.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

namespace AdobeSign.Rest.Test.Model.Agreements
{
    /// <summary>
    ///  Class for testing ReminderCreationResult
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class ReminderCreationResultTests
    {
        // TODO uncomment below to declare an instance variable for ReminderCreationResult
        //private ReminderCreationResult instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of ReminderCreationResult
            //instance = new ReminderCreationResult();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of ReminderCreationResult
        /// </summary>
        [Test]
        public void ReminderCreationResultInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" ReminderCreationResult
            //Assert.IsInstanceOfType<ReminderCreationResult> (instance, "variable 'instance' is a ReminderCreationResult");
        }


        /// <summary>
        /// Test the property 'Id'
        /// </summary>
        [Test]
        public void IdTest()
        {
            // TODO unit test for the property 'Id'
        }

    }

}
