/* 
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 6.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

namespace AdobeSign.Rest.Test.Model.Agreements
{
    /// <summary>
    ///  Class for testing RemindersResponse
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class RemindersResponseTests
    {
        // TODO uncomment below to declare an instance variable for RemindersResponse
        //private RemindersResponse instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of RemindersResponse
            //instance = new RemindersResponse();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of RemindersResponse
        /// </summary>
        [Test]
        public void RemindersResponseInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" RemindersResponse
            //Assert.IsInstanceOfType<RemindersResponse> (instance, "variable 'instance' is a RemindersResponse");
        }


        /// <summary>
        /// Test the property 'ReminderInfoList'
        /// </summary>
        [Test]
        public void ReminderInfoListTest()
        {
            // TODO unit test for the property 'ReminderInfoList'
        }

    }

}
