/* 
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 6.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

namespace AdobeSign.Rest.Test.Model.Agreements
{
    /// <summary>
    ///  Class for testing SigningUrlResponse
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class SigningUrlResponseTests
    {
        // TODO uncomment below to declare an instance variable for SigningUrlResponse
        //private SigningUrlResponse instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of SigningUrlResponse
            //instance = new SigningUrlResponse();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of SigningUrlResponse
        /// </summary>
        [Test]
        public void SigningUrlResponseInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" SigningUrlResponse
            //Assert.IsInstanceOfType<SigningUrlResponse> (instance, "variable 'instance' is a SigningUrlResponse");
        }


        /// <summary>
        /// Test the property 'SigningUrlSetInfos'
        /// </summary>
        [Test]
        public void SigningUrlSetInfosTest()
        {
            // TODO unit test for the property 'SigningUrlSetInfos'
        }

    }

}
