/* 
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 6.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

namespace AdobeSign.Rest.Test.Model.Agreements
{
    /// <summary>
    ///  Class for testing UserAgreements
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class UserAgreementsTests
    {
        // TODO uncomment below to declare an instance variable for UserAgreements
        //private UserAgreements instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of UserAgreements
            //instance = new UserAgreements();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of UserAgreements
        /// </summary>
        [Test]
        public void UserAgreementsInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" UserAgreements
            //Assert.IsInstanceOfType<UserAgreements> (instance, "variable 'instance' is a UserAgreements");
        }


        /// <summary>
        /// Test the property 'Page'
        /// </summary>
        [Test]
        public void PageTest()
        {
            // TODO unit test for the property 'Page'
        }
        /// <summary>
        /// Test the property 'UserAgreementList'
        /// </summary>
        [Test]
        public void UserAgreementListTest()
        {
            // TODO unit test for the property 'UserAgreementList'
        }

    }

}
