/* 
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 6.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

namespace AdobeSign.Rest.Test.Model.Widgets
{
    /// <summary>
    ///  Class for testing DisplayWidgetParticipantSetInfo
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class DisplayWidgetParticipantSetInfoTests
    {
        // TODO uncomment below to declare an instance variable for DisplayWidgetParticipantSetInfo
        //private DisplayWidgetParticipantSetInfo instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of DisplayWidgetParticipantSetInfo
            //instance = new DisplayWidgetParticipantSetInfo();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of DisplayWidgetParticipantSetInfo
        /// </summary>
        [Test]
        public void DisplayWidgetParticipantSetInfoInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" DisplayWidgetParticipantSetInfo
            //Assert.IsInstanceOfType<DisplayWidgetParticipantSetInfo> (instance, "variable 'instance' is a DisplayWidgetParticipantSetInfo");
        }


        /// <summary>
        /// Test the property 'DisplayUserSetMemberInfos'
        /// </summary>
        [Test]
        public void DisplayUserSetMemberInfosTest()
        {
            // TODO unit test for the property 'DisplayUserSetMemberInfos'
        }

    }

}
