/* 
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 6.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

namespace AdobeSign.Rest.Test.Model.Widgets
{
    /// <summary>
    ///  Class for testing Note
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class NoteTests
    {
        // TODO uncomment below to declare an instance variable for Note
        //private Note instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of Note
            //instance = new Note();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of Note
        /// </summary>
        [Test]
        public void NoteInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" Note
            //Assert.IsInstanceOfType<Note> (instance, "variable 'instance' is a Note");
        }


        /// <summary>
        /// Test the property '_Note'
        /// </summary>
        [Test]
        public void _NoteTest()
        {
            // TODO unit test for the property '_Note'
        }

    }

}
