/* 
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 6.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

namespace AdobeSign.Rest.Test.Model.Widgets
{
    /// <summary>
    ///  Class for testing SecurityOption
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class SecurityOptionTests
    {
        // TODO uncomment below to declare an instance variable for SecurityOption
        //private SecurityOption instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of SecurityOption
            //instance = new SecurityOption();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of SecurityOption
        /// </summary>
        [Test]
        public void SecurityOptionInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" SecurityOption
            //Assert.IsInstanceOfType<SecurityOption> (instance, "variable 'instance' is a SecurityOption");
        }


        /// <summary>
        /// Test the property 'OpenPassword'
        /// </summary>
        [Test]
        public void OpenPasswordTest()
        {
            // TODO unit test for the property 'OpenPassword'
        }

    }

}
