/* 
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 6.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

namespace AdobeSign.Rest.Test.Model.Widgets
{
    /// <summary>
    ///  Class for testing VisibilityInfo
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class VisibilityInfoTests
    {
        // TODO uncomment below to declare an instance variable for VisibilityInfo
        //private VisibilityInfo instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of VisibilityInfo
            //instance = new VisibilityInfo();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of VisibilityInfo
        /// </summary>
        [Test]
        public void VisibilityInfoInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" VisibilityInfo
            //Assert.IsInstanceOfType<VisibilityInfo> (instance, "variable 'instance' is a VisibilityInfo");
        }


        /// <summary>
        /// Test the property 'Visibility'
        /// </summary>
        [Test]
        public void VisibilityTest()
        {
            // TODO unit test for the property 'Visibility'
        }

    }

}
