/* 
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 6.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

namespace AdobeSign.Rest.Test.Model.Widgets
{
    /// <summary>
    ///  Class for testing WidgetViews
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class WidgetViewsTests
    {
        // TODO uncomment below to declare an instance variable for WidgetViews
        //private WidgetViews instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of WidgetViews
            //instance = new WidgetViews();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of WidgetViews
        /// </summary>
        [Test]
        public void WidgetViewsInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" WidgetViews
            //Assert.IsInstanceOfType<WidgetViews> (instance, "variable 'instance' is a WidgetViews");
        }


        /// <summary>
        /// Test the property 'WidgetViewList'
        /// </summary>
        [Test]
        public void WidgetViewListTest()
        {
            // TODO unit test for the property 'WidgetViewList'
        }

    }

}
