/* 
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 6.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

namespace AdobeSign.Rest.Test.Model.Widgets
{
    /// <summary>
    ///  Class for testing WidgetDocuments
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class WidgetDocumentsTests
    {
        // TODO uncomment below to declare an instance variable for WidgetDocuments
        //private WidgetDocuments instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of WidgetDocuments
            //instance = new WidgetDocuments();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of WidgetDocuments
        /// </summary>
        [Test]
        public void WidgetDocumentsInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" WidgetDocuments
            //Assert.IsInstanceOfType<WidgetDocuments> (instance, "variable 'instance' is a WidgetDocuments");
        }


        /// <summary>
        /// Test the property 'Documents'
        /// </summary>
        [Test]
        public void DocumentsTest()
        {
            // TODO unit test for the property 'Documents'
        }

    }

}
