/* 
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 6.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

namespace AdobeSign.Rest.Test.Model.Widgets
{
    /// <summary>
    ///  Class for testing WidgetEventDeviceLocation
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class WidgetEventDeviceLocationTests
    {
        // TODO uncomment below to declare an instance variable for WidgetEventDeviceLocation
        //private WidgetEventDeviceLocation instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of WidgetEventDeviceLocation
            //instance = new WidgetEventDeviceLocation();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of WidgetEventDeviceLocation
        /// </summary>
        [Test]
        public void WidgetEventDeviceLocationInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" WidgetEventDeviceLocation
            //Assert.IsInstanceOfType<WidgetEventDeviceLocation> (instance, "variable 'instance' is a WidgetEventDeviceLocation");
        }


        /// <summary>
        /// Test the property 'Latitude'
        /// </summary>
        [Test]
        public void LatitudeTest()
        {
            // TODO unit test for the property 'Latitude'
        }
        /// <summary>
        /// Test the property 'Longitude'
        /// </summary>
        [Test]
        public void LongitudeTest()
        {
            // TODO unit test for the property 'Longitude'
        }

    }

}
