/* 
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 6.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

namespace AdobeSign.Rest.Test.Model.Widgets
{
    /// <summary>
    ///  Class for testing WidgetMembersInfo
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class WidgetMembersInfoTests
    {
        // TODO uncomment below to declare an instance variable for WidgetMembersInfo
        //private WidgetMembersInfo instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of WidgetMembersInfo
            //instance = new WidgetMembersInfo();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of WidgetMembersInfo
        /// </summary>
        [Test]
        public void WidgetMembersInfoInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" WidgetMembersInfo
            //Assert.IsInstanceOfType<WidgetMembersInfo> (instance, "variable 'instance' is a WidgetMembersInfo");
        }


        /// <summary>
        /// Test the property 'AdditionalParticipantSets'
        /// </summary>
        [Test]
        public void AdditionalParticipantSetsTest()
        {
            // TODO unit test for the property 'AdditionalParticipantSets'
        }
        /// <summary>
        /// Test the property 'CcsInfo'
        /// </summary>
        [Test]
        public void CcsInfoTest()
        {
            // TODO unit test for the property 'CcsInfo'
        }
        /// <summary>
        /// Test the property 'CreatorInfo'
        /// </summary>
        [Test]
        public void CreatorInfoTest()
        {
            // TODO unit test for the property 'CreatorInfo'
        }
        /// <summary>
        /// Test the property 'SharesInfo'
        /// </summary>
        [Test]
        public void SharesInfoTest()
        {
            // TODO unit test for the property 'SharesInfo'
        }
        /// <summary>
        /// Test the property 'WidgetParticipantSet'
        /// </summary>
        [Test]
        public void WidgetParticipantSetTest()
        {
            // TODO unit test for the property 'WidgetParticipantSet'
        }

    }

}
