/* 
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 6.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

namespace AdobeSign.Rest.Test.Model.Users
{
    /// <summary>
    ///  Class for testing UserViewResponse
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class UserViewResponseTests
    {
        // TODO uncomment below to declare an instance variable for UserViewResponse
        //private UserViewResponse instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of UserViewResponse
            //instance = new UserViewResponse();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of UserViewResponse
        /// </summary>
        [Test]
        public void UserViewResponseInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" UserViewResponse
            //Assert.IsInstanceOfType<UserViewResponse> (instance, "variable 'instance' is a UserViewResponse");
        }


        /// <summary>
        /// Test the property 'UserViewList'
        /// </summary>
        [Test]
        public void UserViewListTest()
        {
            // TODO unit test for the property 'UserViewList'
        }

    }

}
