/* 
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 6.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

namespace AdobeSign.Rest.Test.Model.LibraryDocuments
{
    /// <summary>
    ///  Class for testing Documents
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class DocumentsTests
    {
        // TODO uncomment below to declare an instance variable for Documents
        //private Documents instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of Documents
            //instance = new Documents();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of Documents
        /// </summary>
        [Test]
        public void DocumentsInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" Documents
            //Assert.IsInstanceOfType<Documents> (instance, "variable 'instance' is a Documents");
        }


        /// <summary>
        /// Test the property '_Documents'
        /// </summary>
        [Test]
        public void _DocumentsTest()
        {
            // TODO unit test for the property '_Documents'
        }

    }

}
