/* 
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 6.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

namespace AdobeSign.Rest.Test.Model.LibraryDocuments
{
    /// <summary>
    ///  Class for testing LibraryDocumentViewResponse
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class LibraryDocumentViewResponseTests
    {
        // TODO uncomment below to declare an instance variable for LibraryDocumentViewResponse
        //private LibraryDocumentViewResponse instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of LibraryDocumentViewResponse
            //instance = new LibraryDocumentViewResponse();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of LibraryDocumentViewResponse
        /// </summary>
        [Test]
        public void LibraryDocumentViewResponseInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" LibraryDocumentViewResponse
            //Assert.IsInstanceOfType<LibraryDocumentViewResponse> (instance, "variable 'instance' is a LibraryDocumentViewResponse");
        }


        /// <summary>
        /// Test the property 'LibraryViewList'
        /// </summary>
        [Test]
        public void LibraryViewListTest()
        {
            // TODO unit test for the property 'LibraryViewList'
        }

    }

}
