/* 
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 6.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

namespace AdobeSign.Rest.Test.Model.LibraryDocuments
{
    /// <summary>
    ///  Class for testing LibraryDocuments
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class LibraryDocumentsTests
    {
        // TODO uncomment below to declare an instance variable for LibraryDocuments
        //private LibraryDocuments instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of LibraryDocuments
            //instance = new LibraryDocuments();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of LibraryDocuments
        /// </summary>
        [Test]
        public void LibraryDocumentsInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" LibraryDocuments
            //Assert.IsInstanceOfType<LibraryDocuments> (instance, "variable 'instance' is a LibraryDocuments");
        }


        /// <summary>
        /// Test the property 'LibraryDocumentList'
        /// </summary>
        [Test]
        public void LibraryDocumentListTest()
        {
            // TODO unit test for the property 'LibraryDocumentList'
        }
        /// <summary>
        /// Test the property 'Page'
        /// </summary>
        [Test]
        public void PageTest()
        {
            // TODO unit test for the property 'Page'
        }

    }

}
